import Title from "@/components/ui/title";
import Block from "@/components/project/block";
import Chip from "@/components/ui/chip";
import Image from "@/components/ui/image";
import image0 from "@/assets/images/jidoka-report-0.jpg";
import image1 from "@/assets/images/jidoka-report-1.jpg";
import image2 from "@/assets/images/jidoka-report-2.jpg";
import { PhotoProvider, PhotoView } from 'react-photo-view';

const techStack = ["C#", "ASP.NET", "React", "Oracle", "MUI", "ApexCharts", "XLSX"];
const gallery = [image0, image1, image2];

export default function JidokaReport() {
  return (
    <div className="max-w-5xl mx-auto px-6 pt-16 pb-20 relative">
      <Title
        title="Jidoka Report"
        description="A reporting dashboard for production stoppages generated by Jidoka events, improving report accuracy by 62%."
        descriptionClassName="font-light"
      />
      <div className="flex flex-col gap-16">
        <Block title="Context & Motivation" image={gallery[0]}>
          <p>In manufacturing environments, Jidoka systems generate production stoppage events used for monitoring, analysis, and audits. The previous reporting logic did not properly account for duplicated or overlapping events, which created inconsistencies in internal and customer-facing reports.</p>
          <p>Because the central Jidoka system synchronizes across multiple databases, certain failure scenarios could inflate stoppage counts or distort historical analysis. The rebuilt Jidoka Report introduced event-grouping and validation logic to provide a more accurate view of line stops.</p>
        </Block>
        <Block
          title="Technologies Used"
        >
          <div className="flex flex-wrap gap-1">
            {techStack.map((tech) => (
              <Chip key={tech} label={tech} />
            ))}
          </div>
        </Block>
        <Block
          title="Key Features"
          image={gallery[1]}
          reverse={true}
        >
          <ul className="list-disc pl-6 space-y-2">
            <li>Automated consolidation of overlapping Jidoka block events.</li>
            <li>Report logic rebuilt to handle duplicated and overlapping events correctly.</li>
            <li>Interactive dashboards with station, line, and downtime analytics.</li>
            <li>Pareto analysis for identifying top root causes of line stops.</li>
            <li>Exportable reports with filtering by date, shift, and production line.</li>
            <li>More reliable data for production analysis, internal audits, and customer audits.</li>
          </ul>
        </Block>
        <Block title="Impact">
          <p>
            Improved Jidoka event reporting accuracy by 62% with rebuilt report logic, resulting in more reliable data for production monitoring, internal audits, and customer audits.
          </p>
        </Block>
        {gallery.length > 2 &&
          <Block
            title="Gallery"
          >
            <PhotoProvider>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {gallery.slice(1).map((image) => (
                  <PhotoView
                    key={image}
                    src={image}
                  >
                    <Image src={image} containerClassName="aspect-video" />
                  </PhotoView>
                ))}
              </div>
            </PhotoProvider>
          </Block>
        }
      </div>
    </div>
  );
}
